# Generated by Django 2.0.2 on 2019-04-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='slag_spreek',
            new_name='employee_no',
        ),
    ]
