# Generated by Django 2.0.2 on 2019-04-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofileinfo_cell_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
