# Generated by Django 2.0.2 on 2019-04-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofileinfo_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
