# Generated by Django 2.0.2 on 2019-04-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clock_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clockentry',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='clockentry',
            name='date',
        ),
    ]
