# Generated by Django 2.0.2 on 2019-04-08 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clock_card', '0002_auto_20190408_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clockentry',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='clockentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
