# Generated by Django 2.0.2 on 2019-04-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_card', '0004_auto_20190408_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockentry',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
