# Generated by Django 2.0.2 on 2019-04-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_card', '0006_auto_20190408_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockentry',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clockentry',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clockentry',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clockentry',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
