# Generated by Django 2.0.2 on 2019-04-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_card', '0007_auto_20190409_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockentry',
            name='clock_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clockentry',
            name='work_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
