# Generated by Django 2.0.2 on 2019-04-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clock_card', '0008_auto_20190409_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clockentry',
            old_name='clock_type',
            new_name='clock_io',
        ),
        migrations.RenameField(
            model_name='clockentry',
            old_name='work_type',
            new_name='work_st',
        ),
    ]
