# Generated by Django 2.0.2 on 2019-04-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_card', '0009_auto_20190409_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockentry',
            name='work_st',
            field=models.CharField(blank=True, choices=[('Work', 'Work'), ('Travel', 'Travel')], default='Work', max_length=100),
        ),
    ]
