# Generated by Django 2.0.2 on 2019-04-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_card', '0011_auto_20190409_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockentry',
            name='clock_io',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clockentry',
            name='work_st',
            field=models.CharField(max_length=100),
        ),
    ]
