# Generated by Django 2.0.2 on 2019-04-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_card', '0012_auto_20190411_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockentry',
            name='hours_worked',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
