# Generated by Django 2.0.2 on 2019-04-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_card', '0013_clockentry_hours_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockentry',
            name='hours_worked',
            field=models.TimeField(),
        ),
    ]
