# Generated by Django 2.0.2 on 2019-04-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock_card', '0014_auto_20190411_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockentry',
            name='hours_worked',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
