# Generated by Django 2.0.2 on 2019-04-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clock_card', '0015_auto_20190411_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clockentry',
            old_name='city',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='clockentry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='clockentry',
            name='state',
        ),
        migrations.RemoveField(
            model_name='clockentry',
            name='street',
        ),
    ]
